main: coderdojo.Plugin
name: SessionGuard
version: 0.0.2
api-version: '1.19'
description: this is a plugin
author: coderdojo_linz
depend:
  - WorldGuard
commands:
  gohome:
    description: go to your plot
    aliases:
    - gehheim
    usage: /<command>
  reset:
    description: reset your plot
    aliases:
      - zurücksetzen
    usage: /<command>
  gowatch:
    description: teleports you to the presenting player
    aliases:
      - gehzuschaun
    usage: /<command>
  watchme:
    description: sets you as the presenting player
    usage: /<command>
    permission: minecraft.command.ban
  go:
    description: go somewhere important
    usage: /<command> (home/watch/library)