main: coderdojo.Plugin
name: SessionGuard
version: '0.1'
description: this is a plugin
author: coderdojo_linz
depend:
  - WorldGuard
commands:
  gohome:
    description: go to your plot
    aliases:
    - gehheim
    usage: /<command>
  reset:
    description: reset your plot
    usage: /<command>
  gowatch:
    description: teleports you to the presenting player
    usage: /<command>
  watchme:
    description: sets you as the presenting player
    usage: /<command>
    permission: minecraft.command.ban
